---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfbuildpacks/ci
inputs:
  - name: ci
  - name: src
  - name: semver.version
  - name: s3.receipt
outputs:
  - name: out
run:
  path: ci/tasks/make-rootfs/run.sh
